// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "adder": Application User Types
//
// Command:
// $ goagen
// --design=github.com/IkuEisou/goa-adder/design
// --out=$(GOPATH)/src/github.com/ikueisou/goa-adder
// --version=v1.3.1

package app
